### ISSUE TITLE
HD кчество

### ISSUE THREAD

**Issue by MaksymBilenko** [weirdgiraffe/plugin.video.giraffe.seasonvar#11]
Ранее было возможно смотреть в HD (как-то модифицировалась ссылка на видеофайл).
Как описано https://github.com/denisukvadim/Seasonvar/blob/master/README.md
Есть возможность имплементировать в плагине?

**Comment by uasash** [comment]
Я прям в реквест добавлял хеадер куки)

**Comment by weirdgiraffe** [comment]
@uasash какие именно куки?

**Comment by weirdgiraffe** [comment]
@MaksymBilenko  А как можно потрогать HD-качество не имея премиума?

**Comment by MaksymBilenko** [comment]
@weirdgiraffe Раньше можно было, сейчас, похоже, закрыли эту лазейку :(

**Comment by weirdgiraffe** [comment]
Недостаточно информации о том, как можно было бы это сделать. Снова открою, если будет больше информации.
