### ISSUE TITLE
Zip repo

### ISSUE THREAD

**Issue by seppius-xbmc-repo** [weirdgiraffe/plugin.video.giraffe.seasonvar#2]
Zip плагина будет для добаваления в сирчер?

**Comment by weirdgiraffe** [comment]
check "releases". you got one there

**Comment by weirdgiraffe** [comment]
два варианта получить архив:

первый:

```bash
git clone https://github.com/weirdgiraffe/plugin.video.giraffe.seasonvar.git
cd plugin.video.giraffe.seasonvar
make
```

второй:

скачать готовый архив отсюда https://github.com/weirdgiraffe/kodi.addon.repo/tree/master/addons/plugin.video.giraffe.seasonvar
