### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 0: ordinal not in range(128) 

### ISSUE THREAD

**Issue by xbmcrepo** [weirdgiraffe/plugin.video.giraffe.seasonvar#6]
Поиск, набранный  Cyrillic (ASCII) в ОС Ubuntu 14.04.5 LTS, Android 4.4.2, Windows 7 завершается ошибкой : 'ascii' codec can't decode byte 0xd1 in position 0: ordinal not in range(128)'
Как решение установить кодировку по умолчанию  UTF-8. 
http://wiki.python.su/Документации/BeautifulSoup
plugin.video.giraffe.seasonvar v.1.2.0  /resources/site-packages/seasonvar/search.py
from urllib import quote
except ImportError: # for python 3.x
from urllib.parse import quote

+import sys
+reload(sys)
+sys.setdefaultencoding("UTF-8")

**Comment by weirdgiraffe** [comment]
Если в версии 0.1.3 все работает, то я закрою это issue

**Comment by seppius-xbmc-repo** [comment]
OK
